version: '1.0'
services:
  trade.aggregator:
    image: TradePriceAggregator
    container_name: trade.aggregator
    build:
      context: .
      dockerfile: TradePriceAggregator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5100:80"
  
  trade.database:
    image: postgres:15
    container_name: trade.database
    environment:
      POSTGRES_DB: "tradedb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
      